// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Comment {
  /**
   * Name
   */
  name: string;

  /**
   * Text
   */
  text: string;

  /**
   * Image of author
   */
  imageId: string;
}
