// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface DefaultPageConfig {
  /**
   * Navbar Title
   */
  navbarTitle?: string;

  /**
   * Navbar color scheme
   */
  navbarColorScheme: "light" | "dark" | "blue";
}
